apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: password-generator
  namespace: services
spec:
  chart:
    spec:
      version: "0.2.0"
  values:
    fullnameOverride: "password-generator"
    replicaCount: 3
    resources:    
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"
    image:
      repository: hanselchristopher001/password-generator
      pullPolicy: IfNotPresent
      tag: "v1.0.0"
    ingress:
      enabled: false
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /$2        
      hosts:
        - host: localhost
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []


