apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: password-generator
  namespace: services
spec:
  chart:
    spec:
      version: "1.0.3"
  values:
    fullnameOverride: "password-generator"
    replicaCount: 3
    resources:    
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"
    image:
      repository: hanselchristopher001/password-generator
      pullPolicy: IfNotPresent
      tag: d635c12
    ingress:
      enabled: true
      className: "nginx"
      hosts:
        - host: localhost
          paths:
            - path: /generate-passwords
              pathType: Prefix
            - path: /
              pathType: Prefix
      tls: []
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 10
      triggers:
        memory:
          value: "80"
    blueGreen:
      autoPromotionEnabled: "false"
      scaleDownDelaySeconds: 60



