apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: core
spec:
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp
  interval: 1h0m0s
  values:
    server:
      affinity: ""
      ha:
        enabled: true
        raft: 
          enabled: true
 
