apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: service-password
  namespace: services
spec:
  chart:
    spec:
      chart: "service-chart"
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: service-chart-repo
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    replicaCount: 1
    resources:    
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"

