apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: service-password
  namespace: services
spec:
  chart:
    spec:
      version: "0.2.0"
  values:
    replicaCount: 3
    resources:    
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"
    image:
      repository: hanselchristopher001/password-generator
      pullPolicy: IfNotPresent
      tag: "v1.0.0"


