apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: service-chart
  namespace: flux-system
spec:
  interval: 5m0s
  url: file:///Users/hanselchristopher/Dev/Cognigy/Kubernetes/service-chart
